### ISSUE TITLE
vobject has no attribute vtodo_list

### ISSUE THREAD

**Issue by ix-** [jspricke/python-icstask#2]
```
 ics2task ~/dl/ww.ics ww.task
   Traceback (most recent call last):
  File "/tmp/spam/lib/python3.6/site-packages/vobject/base.py", line 527, in __getattr__
     return self.contents[toVName(name, 5)]
 KeyError: 'vtodo'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/tmp/spam/bin/ics2task", line 11, in <module>
    sys.exit(ics2task())
   File "/tmp/spam/lib/python3.6/site-packages/icstask.py", line 301, in ics2task
    for todo in vobject.vtodo_list:
   File "/tmp/spam/lib/python3.6/site-packages/vobject/base.py", line 531, in __getattr__
     raise AttributeError(name)
  AttributeError: vtodo_list

```

https://github.com/jspricke/python-icstask/blob/93d2686daee24730b7659b841289acb904bb936a/icstask.py#L302

Best regards,
ix

**Comment by jspricke** [comment]
Hey, can you append the content of `~/dl/ww.ics` so I can try it over here? (Make sure not to include private information).

**Comment by ix-** [comment]
had to rename it, as gh does not support ics (as extention...)
[ww.txt](https://github.com/jspricke/python-icstask/files/1780051/ww.txt)

**Comment by jspricke** [comment]
Well, it contains no vtodo entries (as the error message says). What would you expect `ics2task` to do with it?

**Comment by ix-** [comment]
I'd like it to record the dates as scheduled. Ok, maybe I did not really understand what the ics2task does. Than I'm sorry.

**Comment by jspricke** [comment]
We could write a simple script to convert vevents to vtodos, but I don't see it as part of this project.

**Comment by ix-** [comment]
Ok, what I expected:
- ics2task reads the ics file
- the ics files contains events
- the events are recorded in taskwarrior as scheduled.

If you do not see this as part of the project, mark the issue as closed.
Thanks

**Comment by jspricke** [comment]
ics files can contain `VEVENT`, `VTODO` and `VJOURNAL` entries. `ics2task` only handles the `VTODO` part. You can try this as a start:
``
sed -s 's/VEVENT/VTODO/g' ww.ics | ics2task
``

**Comment by ix-** [comment]
Thx!
Maybe include this in the readme, this was not clear to me.
Best regards.

**Comment by jspricke** [comment]
Done, thanks for coming up with this :). Is the sed call enough for you, already?

**Comment by jspricke** [comment]
maybe you rather want something like this?
``
sed -e 's/VEVENT/VTODO/' -e 's/DTSTART/DUE/' ww.ics | ics2task
``
